http://pc11.2ch.net/test/read.cgi/unix/1156781437/828

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -272,7 +272,7 @@ PACKAGE_STRING=
 PACKAGE_BUGREPORT=
 
 ac_unique_file="navi2ch.el"
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT EMACS EMACSLOADPATH lispdir packagedir icondir LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT build build_cpu build_vendor build_os host host_cpu host_vendor host_os CVS LN_S EMACS packagedir lispdir icondir LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -713,14 +713,6 @@ ac_env_target_alias_set=${target_alias+set}
 ac_env_target_alias_value=$target_alias
 ac_cv_env_target_alias_set=${target_alias+set}
 ac_cv_env_target_alias_value=$target_alias
-ac_env_EMACS_set=${EMACS+set}
-ac_env_EMACS_value=$EMACS
-ac_cv_env_EMACS_set=${EMACS+set}
-ac_cv_env_EMACS_value=$EMACS
-ac_env_EMACSLOADPATH_set=${EMACSLOADPATH+set}
-ac_env_EMACSLOADPATH_value=$EMACSLOADPATH
-ac_cv_env_EMACSLOADPATH_set=${EMACSLOADPATH+set}
-ac_cv_env_EMACSLOADPATH_value=$EMACSLOADPATH
 
 #
 # Report the --help message.
@@ -786,6 +778,10 @@ Program names:
   --program-prefix=PREFIX            prepend PREFIX to installed program names
   --program-suffix=SUFFIX            append SUFFIX to installed program names
   --program-transform-name=PROGRAM   run sed PROGRAM on installed program names
+
+System types:
+  --build=BUILD     configure for building on BUILD [guessed]
+  --host=HOST       cross-compile to build programs to run on HOST [BUILD]
 _ACEOF
 fi
 
@@ -802,19 +798,14 @@ Optional Features:
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
-  --with-lispdir          override the default lisp directory
+  --with-bash             Use Bash to build
+  --with-xemacs           Use XEmacs to build
+  --with-emacs            Use Emacs to build
   --with-packagedir[=DIR] Use package directory
                           (With XEmacs, this option also sets
                            icondir, lispdir, infodir, etc...)
+  --with-lispdir          Override the default lisp directory
   --with-icondir=DIR      Override the default icons directory
-
-Some influential environment variables:
-  EMACS       the Emacs editor command
-  EMACSLOADPATH
-              the Emacs library search path
-
-Use these variables to override the choices made by `configure' or to help
-it to find libraries and programs with nonstandard names/locations.
 
 _ACEOF
 fi
@@ -1715,10 +1706,161 @@ fi
 
 
 
- # If set to t, that means we are running in a shell under Emacs.
- # If you have an Emacs named "t", then use the full path.
- test x"$EMACS" = xt && EMACS=
- for ac_prog in emacs xemacs
+# Emacs set environment variable EMACS as t
+test "x$EMACS" = xt && unset EMACS
+
+emacsen="emacs xemacs"
+
+# Make sure we can run config.sub.
+$ac_config_sub sun4 >/dev/null 2>&1 ||
+  { { echo "$as_me:$LINENO: error: cannot run $ac_config_sub" >&5
+echo "$as_me: error: cannot run $ac_config_sub" >&2;}
+   { (exit 1); exit 1; }; }
+
+echo "$as_me:$LINENO: checking build system type" >&5
+echo $ECHO_N "checking build system type... $ECHO_C" >&6
+if test "${ac_cv_build+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_build_alias=$build_alias
+test -z "$ac_cv_build_alias" &&
+  ac_cv_build_alias=`$ac_config_guess`
+test -z "$ac_cv_build_alias" &&
+  { { echo "$as_me:$LINENO: error: cannot guess build type; you must specify one" >&5
+echo "$as_me: error: cannot guess build type; you must specify one" >&2;}
+   { (exit 1); exit 1; }; }
+ac_cv_build=`$ac_config_sub $ac_cv_build_alias` ||
+  { { echo "$as_me:$LINENO: error: $ac_config_sub $ac_cv_build_alias failed" >&5
+echo "$as_me: error: $ac_config_sub $ac_cv_build_alias failed" >&2;}
+   { (exit 1); exit 1; }; }
+
+fi
+echo "$as_me:$LINENO: result: $ac_cv_build" >&5
+echo "${ECHO_T}$ac_cv_build" >&6
+build=$ac_cv_build
+build_cpu=`echo $ac_cv_build | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\1/'`
+build_vendor=`echo $ac_cv_build | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\2/'`
+build_os=`echo $ac_cv_build | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
+
+
+echo "$as_me:$LINENO: checking host system type" >&5
+echo $ECHO_N "checking host system type... $ECHO_C" >&6
+if test "${ac_cv_host+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_host_alias=$host_alias
+test -z "$ac_cv_host_alias" &&
+  ac_cv_host_alias=$ac_cv_build_alias
+ac_cv_host=`$ac_config_sub $ac_cv_host_alias` ||
+  { { echo "$as_me:$LINENO: error: $ac_config_sub $ac_cv_host_alias failed" >&5
+echo "$as_me: error: $ac_config_sub $ac_cv_host_alias failed" >&2;}
+   { (exit 1); exit 1; }; }
+
+fi
+echo "$as_me:$LINENO: result: $ac_cv_host" >&5
+echo "${ECHO_T}$ac_cv_host" >&6
+host=$ac_cv_host
+host_cpu=`echo $ac_cv_host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\1/'`
+host_vendor=`echo $ac_cv_host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\2/'`
+host_os=`echo $ac_cv_host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
+
+
+
+case "$host_os" in
+*cygwin*)
+  with_bash=yes
+  emacsen="$emacsen MeadowNT.exe Meadow95.exe"
+  ;;
+esac
+
+
+# Check whether --with-bash or --without-bash was given.
+if test "${with_bash+set}" = set; then
+  withval="$with_bash"
+  case "$withval" in
+yes) SHELL=bash ;;
+no)  ;;
+*)   SHELL="$withval" ;;
+esac
+fi;
+
+
+# Check whether --with-xemacs or --without-xemacs was given.
+if test "${with_xemacs+set}" = set; then
+  withval="$with_xemacs"
+  case "$withval" in
+yes) emacsen="xemacs" ;;
+no)  emacsen="emacs" ;;
+*)   EMACS="$withval" ;;
+esac
+fi;
+
+
+# Check whether --with-emacs or --without-emacs was given.
+if test "${with_emacs+set}" = set; then
+  withval="$with_emacs"
+  case "$withval" in
+yes) emacsen="emacs" ;;
+no)  emacsen="xemacs" ;;
+*)   EMACS="$withval" ;;
+esac
+fi;
+
+if test -n "${with_xemacs+set}" && test -n "${with_emacs+set}"; then
+  { { echo "$as_me:$LINENO: error: specify one of --with-xemacs or --with-emacs" >&5
+echo "$as_me: error: specify one of --with-xemacs or --with-emacs" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+# Extract the first word of "cvs", so it can be a program name with args.
+set dummy cvs; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_prog_CVS+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test -n "$CVS"; then
+  ac_cv_prog_CVS="$CVS" # Let the user override the test.
+else
+as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_prog_CVS="cvs -z3"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  test -z "$ac_cv_prog_CVS" && ac_cv_prog_CVS=":"
+fi
+fi
+CVS=$ac_cv_prog_CVS
+if test -n "$CVS"; then
+  echo "$as_me:$LINENO: result: $CVS" >&5
+echo "${ECHO_T}$CVS" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+echo "$as_me:$LINENO: checking whether ln -s works" >&5
+echo $ECHO_N "checking whether ln -s works... $ECHO_C" >&6
+LN_S=$as_ln_s
+if test "$LN_S" = "ln -s"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+else
+  echo "$as_me:$LINENO: result: no, using $LN_S" >&5
+echo "${ECHO_T}no, using $LN_S" >&6
+fi
+
+
+for ac_prog in ${emacsen}
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
@@ -1759,55 +1901,11 @@ fi
 done
 test -n "$EMACS" || EMACS="no"
 
-
-
-
-# Check whether --with-lispdir or --without-lispdir was given.
-if test "${with_lispdir+set}" = set; then
-  withval="$with_lispdir"
-   lispdir="$withval"
-   echo "$as_me:$LINENO: checking where .elc files should go" >&5
-echo $ECHO_N "checking where .elc files should go... $ECHO_C" >&6
-   echo "$as_me:$LINENO: result: $lispdir" >&5
-echo "${ECHO_T}$lispdir" >&6
-else
-
- echo "$as_me:$LINENO: checking where .elc files should go" >&5
-echo $ECHO_N "checking where .elc files should go... $ECHO_C" >&6
-if test "${am_cv_lispdir+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-
-   if test $EMACS != "no"; then
-     if test x${lispdir+set} != xset; then
-  # If $EMACS isn't GNU Emacs or XEmacs, this can blow up pretty badly
-  # Some emacsen will start up in interactive mode, requiring C-x C-c to exit,
-  #  which is non-obvious for non-emacs users.
-  # Redirecting /dev/null should help a bit; pity we can't detect "broken"
-  #  emacsen earlier and avoid running this altogether.
-  { (echo "$as_me:$LINENO: \$EMACS -batch -q -eval '(while load-path (princ (concat (car load-path) \"\\n\")) (setq load-path (cdr load-path)))' </dev/null >conftest.out") >&5
-  ($EMACS -batch -q -eval '(while load-path (princ (concat (car load-path) "\n")) (setq load-path (cdr load-path)))' </dev/null >conftest.out) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }
-	am_cv_lispdir=`sed -n \
-       -e 's,/$,,' \
-       -e '/.*\/lib\/x*emacs\/site-lisp$/{s,.*/lib/\(x*emacs/site-lisp\)$,${libdir}/\1,;p;q;}' \
-       -e '/.*\/share\/x*emacs\/site-lisp$/{s,.*/share/\(x*emacs/site-lisp\),${datadir}/\1,;p;q;}' \
-       conftest.out`
-       rm conftest.out
-     fi
-   fi
-   test -z "$am_cv_lispdir" && am_cv_lispdir='${datadir}/emacs/site-lisp'
-
+if test "$EMACS" = "no"; then
+  { { echo "$as_me:$LINENO: error: cannot find emacs" >&5
+echo "$as_me: error: cannot find emacs" >&2;}
+   { (exit 1); exit 1; }; }
 fi
-echo "$as_me:$LINENO: result: $am_cv_lispdir" >&5
-echo "${ECHO_T}$am_cv_lispdir" >&6
-  lispdir="$am_cv_lispdir"
-
-fi;
-
-
 
 echo "$as_me:$LINENO: checking detecting your emacs type" >&5
 echo $ECHO_N "checking detecting your emacs type... $ECHO_C" >&6
@@ -1875,6 +1973,55 @@ if test "$emacstype" = xemacs && test -n "$packagedir"; then
 fi
 
 
+# Check whether --with-lispdir or --without-lispdir was given.
+if test "${with_lispdir+set}" = set; then
+  withval="$with_lispdir"
+   lispdir="$withval"
+    echo "$as_me:$LINENO: checking where .elc files should go" >&5
+echo $ECHO_N "checking where .elc files should go... $ECHO_C" >&6
+    echo "$as_me:$LINENO: result: $lispdir" >&5
+echo "${ECHO_T}$lispdir" >&6
+else
+
+  if test x${lispdir+set} != xset; then
+    echo "$as_me:$LINENO: checking where .elc files should go" >&5
+echo $ECHO_N "checking where .elc files should go... $ECHO_C" >&6
+if test "${am_cv_lispdir+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+        { ac_temp=./conftemp.$$
+ac_output=confout.$$
+rm -f $ac_temp $ac_output
+cat >$ac_temp <<\_ACEOF
+(defun ac-temp-func ()
+(defvar result nil)
+(while load-path
+  (if (string-match "\\`\\(.+/site-lisp\\)/?\\'" (car load-path))
+      (setq result (match-string 1 (car load-path))
+            load-path nil)
+    (setq load-path (cdr load-path))))
+(princ (or result (expand-file-name "../site-lisp" data-directory)))
+(princ "\n") ; make sure the output has trailing newline.
+)
+_ACEOF
+$EMACS -batch -q -l $ac_temp -f ac-temp-func | sed -e '/^ *$/d' > $ac_output
+am_cv_lispdir=`cat $ac_output`
+rm -f $ac_temp $ac_output; }
+      if test -z "$am_cv_lispdir"; then
+	am_cv_lispdir='${datadir}/emacs/site-lisp'
+      fi
+      am_cv_lispdir="$am_cv_lispdir/navi2ch"
+
+fi
+echo "$as_me:$LINENO: result: $am_cv_lispdir" >&5
+echo "${ECHO_T}$am_cv_lispdir" >&6
+    lispdir="$am_cv_lispdir"
+  fi
+
+fi;
+
+
+
 # Check whether --with-icondir or --without-icondir was given.
 if test "${with_icondir+set}" = set; then
   withval="$with_icondir"
@@ -1917,7 +2064,7 @@ fi;
 
 
 
-                                                  ac_config_files="$ac_config_files Makefile contrib/Makefile doc/Makefile icons/Makefile navi2ch-config.el"
+                                        ac_config_files="$ac_config_files Makefile contrib/Makefile doc/Makefile icons/Makefile"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -2480,7 +2627,6 @@ do
   "contrib/Makefile" ) CONFIG_FILES="$CONFIG_FILES contrib/Makefile" ;;
   "doc/Makefile" ) CONFIG_FILES="$CONFIG_FILES doc/Makefile" ;;
   "icons/Makefile" ) CONFIG_FILES="$CONFIG_FILES icons/Makefile" ;;
-  "navi2ch-config.el" ) CONFIG_FILES="$CONFIG_FILES navi2ch-config.el" ;;
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
@@ -2589,10 +2735,19 @@ s,@am__untar@,$am__untar,;t t
 s,@MAINTAINER_MODE_TRUE@,$MAINTAINER_MODE_TRUE,;t t
 s,@MAINTAINER_MODE_FALSE@,$MAINTAINER_MODE_FALSE,;t t
 s,@MAINT@,$MAINT,;t t
+s,@build@,$build,;t t
+s,@build_cpu@,$build_cpu,;t t
+s,@build_vendor@,$build_vendor,;t t
+s,@build_os@,$build_os,;t t
+s,@host@,$host,;t t
+s,@host_cpu@,$host_cpu,;t t
+s,@host_vendor@,$host_vendor,;t t
+s,@host_os@,$host_os,;t t
+s,@CVS@,$CVS,;t t
+s,@LN_S@,$LN_S,;t t
 s,@EMACS@,$EMACS,;t t
-s,@EMACSLOADPATH@,$EMACSLOADPATH,;t t
-s,@lispdir@,$lispdir,;t t
 s,@packagedir@,$packagedir,;t t
+s,@lispdir@,$lispdir,;t t
 s,@icondir@,$icondir,;t t
 s,@LIBOBJS@,$LIBOBJS,;t t
 s,@LTLIBOBJS@,$LTLIBOBJS,;t t
