* navi2ch-version.el.in: template of navi2ch-version.el: set navi2ch-version acording to configure.in * Makefile.am: create navi2ch-version.el from navi2ch-version.el.in make snap makes snapshot. * configure.in: add Meadow*.exe under Cygwin. http://pc.2ch.net/test/read.cgi/unix/1009340234/259 set environment variable EMACS to null if EMACS=t (other files are ganerated automatically)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1224,13 +1224,18 @@ INSTALL_STRIP_PROGRAM="\${SHELL} \$(install_sh) -c -s"
 # We need awk for the "check" target.  The system "awk" is bad on
 # some platforms.
 
+# Emacs set environment variable EMACS as t
+test "x$EMACS" = xt && EMACS=
+
+emacsen="emacs xemacs"
+
 # Make sure we can run config.sub.
 $ac_config_sub sun4 >/dev/null 2>&1 ||
-  { { echo "$as_me:1229: error: cannot run $ac_config_sub" >&5
+  { { echo "$as_me:1234: error: cannot run $ac_config_sub" >&5
 echo "$as_me: error: cannot run $ac_config_sub" >&2;}
    { (exit 1); exit 1; }; }
 
-echo "$as_me:1233: checking build system type" >&5
+echo "$as_me:1238: checking build system type" >&5
 echo $ECHO_N "checking build system type... $ECHO_C" >&6
 if test "${ac_cv_build+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1239,23 +1244,23 @@ else
 test -z "$ac_cv_build_alias" &&
   ac_cv_build_alias=`$ac_config_guess`
 test -z "$ac_cv_build_alias" &&
-  { { echo "$as_me:1242: error: cannot guess build type; you must specify one" >&5
+  { { echo "$as_me:1247: error: cannot guess build type; you must specify one" >&5
 echo "$as_me: error: cannot guess build type; you must specify one" >&2;}
    { (exit 1); exit 1; }; }
 ac_cv_build=`$ac_config_sub $ac_cv_build_alias` ||
-  { { echo "$as_me:1246: error: $ac_config_sub $ac_cv_build_alias failed." >&5
+  { { echo "$as_me:1251: error: $ac_config_sub $ac_cv_build_alias failed." >&5
 echo "$as_me: error: $ac_config_sub $ac_cv_build_alias failed." >&2;}
    { (exit 1); exit 1; }; }
 
 fi
-echo "$as_me:1251: result: $ac_cv_build" >&5
+echo "$as_me:1256: result: $ac_cv_build" >&5
 echo "${ECHO_T}$ac_cv_build" >&6
 build=$ac_cv_build
 build_cpu=`echo $ac_cv_build | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\1/'`
 build_vendor=`echo $ac_cv_build | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\2/'`
 build_os=`echo $ac_cv_build | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
 
-echo "$as_me:1258: checking host system type" >&5
+echo "$as_me:1263: checking host system type" >&5
 echo $ECHO_N "checking host system type... $ECHO_C" >&6
 if test "${ac_cv_host+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1264,12 +1269,12 @@ else
 test -z "$ac_cv_host_alias" &&
   ac_cv_host_alias=$ac_cv_build_alias
 ac_cv_host=`$ac_config_sub $ac_cv_host_alias` ||
-  { { echo "$as_me:1267: error: $ac_config_sub $ac_cv_host_alias failed" >&5
+  { { echo "$as_me:1272: error: $ac_config_sub $ac_cv_host_alias failed" >&5
 echo "$as_me: error: $ac_config_sub $ac_cv_host_alias failed" >&2;}
    { (exit 1); exit 1; }; }
 
 fi
-echo "$as_me:1272: result: $ac_cv_host" >&5
+echo "$as_me:1277: result: $ac_cv_host" >&5
 echo "${ECHO_T}$ac_cv_host" >&6
 host=$ac_cv_host
 host_cpu=`echo $ac_cv_host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\1/'`
@@ -1277,7 +1282,10 @@ host_vendor=`echo $ac_cv_host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\2/'`
 host_os=`echo $ac_cv_host | sed 's/^\([^-]*\)-\([^-]*\)-\(.*\)$/\3/'`
 
 case $host_os in
-*cygwin*) with_bash=yes ;;
+*cygwin*)
+  with_bash=yes
+  emacsen="$emacsen MeadowNT.exe Meadow95.exe"
+  ;;
 esac
 
 # Check whether --with-bash or --without-bash was given.
@@ -1289,8 +1297,6 @@ no)  ;;
 *)   SHELL="$withval" ;;
 esac
 fi;
-
-emacsen="emacs xemacs"
 
 # Check whether --with-xemacs or --without-xemacs was given.
 if test "${with_xemacs+set}" = set; then
@@ -1313,7 +1319,7 @@ esac
 fi;
 
 if test -n "${with_xemacs+set}" && test -n "${with_emacs+set}"; then
-  { { echo "$as_me:1316: error: specify one of --with-xemacs or --with-emacs" >&5
+  { { echo "$as_me:1322: error: specify one of --with-xemacs or --with-emacs" >&5
 echo "$as_me: error: specify one of --with-xemacs or --with-emacs" >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -1322,9 +1328,9 @@ fi
 if test "${with_lispdir+set}" = set; then
   withval="$with_lispdir"
    lispdir="$withval"
-    echo "$as_me:1325: checking where .elc files should go" >&5
+    echo "$as_me:1331: checking where .elc files should go" >&5
 echo $ECHO_N "checking where .elc files should go... $ECHO_C" >&6
-    echo "$as_me:1327: result: $lispdir" >&5
+    echo "$as_me:1333: result: $lispdir" >&5
 echo "${ECHO_T}$lispdir" >&6
 else
 
@@ -1335,7 +1341,7 @@ else
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
-echo "$as_me:1338: checking for $ac_word" >&5
+echo "$as_me:1344: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_prog_EMACS+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1350,7 +1356,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   $as_executable_p "$ac_dir/$ac_word" || continue
 ac_cv_prog_EMACS="$ac_prog"
-echo "$as_me:1353: found $ac_dir/$ac_word" >&5
+echo "$as_me:1359: found $ac_dir/$ac_word" >&5
 break
 done
 
@@ -1358,10 +1364,10 @@ fi
 fi
 EMACS=$ac_cv_prog_EMACS
 if test -n "$EMACS"; then
-  echo "$as_me:1361: result: $EMACS" >&5
+  echo "$as_me:1367: result: $EMACS" >&5
 echo "${ECHO_T}$EMACS" >&6
 else
-  echo "$as_me:1364: result: no" >&5
+  echo "$as_me:1370: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -1370,12 +1376,12 @@ done
 test -n "$EMACS" || EMACS="no"
 
   if test $EMACS = "no"; then
-    { { echo "$as_me:1373: error: cannot find emacs" >&5
+    { { echo "$as_me:1379: error: cannot find emacs" >&5
 echo "$as_me: error: cannot find emacs" >&2;}
    { (exit 1); exit 1; }; }
   fi
   if test x${lispdir+set} != xset; then
-    echo "$as_me:1378: checking where .elc files should go" >&5
+    echo "$as_me:1384: checking where .elc files should go" >&5
 echo $ECHO_N "checking where .elc files should go... $ECHO_C" >&6
 if test "${am_cv_lispdir+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1387,7 +1393,7 @@ else
       am_cv_lispdir="$am_cv_lispdir/navi2ch"
 
 fi
-echo "$as_me:1390: result: $am_cv_lispdir" >&5
+echo "$as_me:1396: result: $am_cv_lispdir" >&5
 echo "${ECHO_T}$am_cv_lispdir" >&6
     lispdir="$am_cv_lispdir"
   fi
@@ -1504,7 +1510,7 @@ rm -f confdef2opt.sed
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:1507: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:1513: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -1672,7 +1678,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:1675: error: ambiguous option: $1
+    { { echo "$as_me:1681: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1691,7 +1697,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:1694: error: unrecognized option: $1
+  -*) { { echo "$as_me:1700: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1728,7 +1734,7 @@ do
   # Handling of arguments.
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
   "doc/Makefile" ) CONFIG_FILES="$CONFIG_FILES doc/Makefile" ;;
-  *) { { echo "$as_me:1731: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:1737: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -1953,7 +1959,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:1956: creating $ac_file" >&5
+    { echo "$as_me:1962: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -1971,7 +1977,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:1974: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:1980: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -1984,7 +1990,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:1987: error: cannot find input file: $f" >&5
+           { { echo "$as_me:1993: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
