add contrib as subdir: now "make dist" includes contrib as distribution.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1451,7 +1451,7 @@ fi
 
 fi;
 
-ac_config_files="$ac_config_files Makefile doc/Makefile icons/Makefile"
+ac_config_files="$ac_config_files Makefile contrib/Makefile doc/Makefile icons/Makefile"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -1784,9 +1784,10 @@ do
   case "$ac_config_target" in
   # Handling of arguments.
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
+  "contrib/Makefile" ) CONFIG_FILES="$CONFIG_FILES contrib/Makefile" ;;
   "doc/Makefile" ) CONFIG_FILES="$CONFIG_FILES doc/Makefile" ;;
   "icons/Makefile" ) CONFIG_FILES="$CONFIG_FILES icons/Makefile" ;;
-  *) { { echo "$as_me:1789: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:1790: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -2015,7 +2016,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:2018: creating $ac_file" >&5
+    { echo "$as_me:2019: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -2033,7 +2034,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:2036: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:2037: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -2046,7 +2047,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:2049: error: cannot find input file: $f" >&5
+           { { echo "$as_me:2050: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
