fix EMACS check bug Thanks! http://pc.2ch.net/test/read.cgi/unix/1009340234/345

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1347,24 +1347,11 @@ echo "$as_me: error: specify one of --with-xemacs or --with-emacs" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
-# Check whether --with-lispdir or --without-lispdir was given.
-if test "${with_lispdir+set}" = set; then
-  withval="$with_lispdir"
-   lispdir="$withval"
-    echo "$as_me:1354: checking where .elc files should go" >&5
-echo $ECHO_N "checking where .elc files should go... $ECHO_C" >&6
-    echo "$as_me:1356: result: $lispdir" >&5
-echo "${ECHO_T}$lispdir" >&6
-else
-
-  # If set to t, that means we are running in a shell under Emacs.
-  # If you have an Emacs named "t", then use the full path.
-  test x"$EMACS" = xt && EMACS=
-  for ac_prog in ${emacsen}
+for ac_prog in ${emacsen}
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
-echo "$as_me:1367: checking for $ac_word" >&5
+echo "$as_me:1354: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_prog_EMACS+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1379,7 +1366,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   $as_executable_p "$ac_dir/$ac_word" || continue
 ac_cv_prog_EMACS="$ac_prog"
-echo "$as_me:1382: found $ac_dir/$ac_word" >&5
+echo "$as_me:1369: found $ac_dir/$ac_word" >&5
 break
 done
 
@@ -1387,10 +1374,10 @@ fi
 fi
 EMACS=$ac_cv_prog_EMACS
 if test -n "$EMACS"; then
-  echo "$as_me:1390: result: $EMACS" >&5
+  echo "$as_me:1377: result: $EMACS" >&5
 echo "${ECHO_T}$EMACS" >&6
 else
-  echo "$as_me:1393: result: no" >&5
+  echo "$as_me:1380: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -1398,13 +1385,24 @@ fi
 done
 test -n "$EMACS" || EMACS="no"
 
-  if test $EMACS = "no"; then
-    { { echo "$as_me:1402: error: cannot find emacs" >&5
+if test $EMACS = "no"; then
+  { { echo "$as_me:1389: error: cannot find emacs" >&5
 echo "$as_me: error: cannot find emacs" >&2;}
    { (exit 1); exit 1; }; }
-  fi
+fi
+
+# Check whether --with-lispdir or --without-lispdir was given.
+if test "${with_lispdir+set}" = set; then
+  withval="$with_lispdir"
+   lispdir="$withval"
+    echo "$as_me:1398: checking where .elc files should go" >&5
+echo $ECHO_N "checking where .elc files should go... $ECHO_C" >&6
+    echo "$as_me:1400: result: $lispdir" >&5
+echo "${ECHO_T}$lispdir" >&6
+else
+
   if test x${lispdir+set} != xset; then
-    echo "$as_me:1407: checking where .elc files should go" >&5
+    echo "$as_me:1405: checking where .elc files should go" >&5
 echo $ECHO_N "checking where .elc files should go... $ECHO_C" >&6
 if test "${am_cv_lispdir+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -1416,7 +1414,7 @@ else
       am_cv_lispdir="$am_cv_lispdir/navi2ch"
 
 fi
-echo "$as_me:1419: result: $am_cv_lispdir" >&5
+echo "$as_me:1417: result: $am_cv_lispdir" >&5
 echo "${ECHO_T}$am_cv_lispdir" >&6
     lispdir="$am_cv_lispdir"
   fi
@@ -1533,7 +1531,7 @@ rm -f confdef2opt.sed
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:1536: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:1534: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -1701,7 +1699,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:1704: error: ambiguous option: $1
+    { { echo "$as_me:1702: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1720,7 +1718,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:1723: error: unrecognized option: $1
+  -*) { { echo "$as_me:1721: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -1757,7 +1755,7 @@ do
   # Handling of arguments.
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
   "doc/Makefile" ) CONFIG_FILES="$CONFIG_FILES doc/Makefile" ;;
-  *) { { echo "$as_me:1760: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:1758: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -1985,7 +1983,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:1988: creating $ac_file" >&5
+    { echo "$as_me:1986: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -2003,7 +2001,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:2006: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:2004: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -2016,7 +2014,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:2019: error: cannot find input file: $f" >&5
+           { { echo "$as_me:2017: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
