navi2ch-e21.el: New file for Emacs21. icons: New directory for icon files.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1421,7 +1421,7 @@ echo "${ECHO_T}$am_cv_lispdir" >&6
 
 fi;
 
-ac_config_files="$ac_config_files Makefile doc/Makefile"
+ac_config_files="$ac_config_files Makefile doc/Makefile icons/Makefile"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -1755,7 +1755,8 @@ do
   # Handling of arguments.
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
   "doc/Makefile" ) CONFIG_FILES="$CONFIG_FILES doc/Makefile" ;;
-  *) { { echo "$as_me:1758: error: invalid argument: $ac_config_target" >&5
+  "icons/Makefile" ) CONFIG_FILES="$CONFIG_FILES icons/Makefile" ;;
+  *) { { echo "$as_me:1759: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -1983,7 +1984,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:1986: creating $ac_file" >&5
+    { echo "$as_me:1987: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -2001,7 +2002,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:2004: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:2005: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -2014,7 +2015,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:2017: error: cannot find input file: $f" >&5
+           { { echo "$as_me:2018: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
